docker.yml edit

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -46,6 +46,19 @@ jobs:
       run: |
         sed -i 's/tag:.*/tag: "${{ steps.get_version.outputs.version }}"/g' ./project/values.yaml
 
+    - name: Execute helm lint
+      run: |
+        helm lint ./project
+        if [ $? -eq 0 ]; then
+          echo "Helm lint passed successfully"
+          echo "SLACK_COLOR=good" >> $GITHUB_ENV
+          echo "SLACK_MESSAGE=Helm lint passed successfully :white_check_mark:" >> $GITHUB_ENV
+        else
+          echo "Helm lint failed"
+          echo "SLACK_COLOR=danger" >> $GITHUB_ENV
+          echo "SLACK_MESSAGE=Helm lint failed :x:" >> $GITHUB_ENV
+        fi
+
     - name: Set up SSH keys
       run: |
         sudo apt-get install -y openssh-client
@@ -71,6 +84,19 @@ jobs:
         SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
         SLACK_ICON: https://github.com/rtCamp.png?size=48
         SLACK_MESSAGE: 'New Image version ${{ steps.get_version.outputs.version }} :rocket:'
+        SLACK_TITLE: Post Title
+        SLACK_USERNAME: rtCamp
+        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+      with:
+       status: ${{ job.status }}
+
+    - name: Slack Notification helm lint
+      uses: rtCamp/action-slack-notify@v2
+      env:
+        SLACK_CHANNEL: 'incoming-webhooks'
+        SLACK_COLOR: ${{ env.SLACK_COLOR }}
+        SLACK_ICON: https://github.com/rtCamp.png?size=48
+        SLACK_MESSAGE: '${{ env.SLACK_MESSAGE }}'
         SLACK_TITLE: Post Title
         SLACK_USERNAME: rtCamp
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
